[package]
name = "cew"
version = "0.1.0"
edition = "2021"
description = "Reexports of `color_eyre` to be quicker to type."
license = "MIT OR Apache-2.0"
repository = "https://github.com/Koranir/cew"
keywords = ["utility", "simple", "logging"]
categories = ["Rust patterns"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = { version = "0.6.2", default-features = false }

[profile.dev.package.backtrace]
opt-level = 3

[features]
default = ["track-caller", "capture-spantrace"]
track-caller = ["color-eyre/track-caller"]
capture-spantrace = ["color-eyre/capture-spantrace"]
url = ["color-eyre/issue-url"]
